apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2 # Let's run 2 pods for fun
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: fastapi-app:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
